version: '3.6'
services:
  db:
    image: postgres
    container_name: alerts_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGPORT=5432
    volumes:
      - type: volume
        source: alerts-postgres-data
        target: /var/lib/postgresql/data
      - type: volume
        source: alerts-postgres-home
        target: /nonexistent
  web:
    build:
      context: .
      dockerfile: Dockerfile.PhoenixAlerts
    container_name: alerts_phoenix
    volumes:
      - type: bind
        source: ./alerts
        target: /app
      - type: bind
        source: ./files
        target: /files
      - type: volume
        source: alerts-elixir-home
        target: /nonexistent
    ports:
      - "4000:4000"
    depends_on:
      - db
    command:
      - ./bin/boot.sh

  # https://github.com/cirocosta/gitserver-http
  gitlist:
    image: "davibe/gitlist-docker"
    container_name: alerts_gitlist
    volumes:
      - type: bind
        source: ./files
        target: /repos
    ports:
      - "8080:80"

  # just for testing -----
  test_mysql:
    build:
      context: .
      dockerfile: Dockerfile.MySqlTest
    image: mysql:latest
    container_name: test_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - secure-file-priv=/data
    volumes:
      - type: bind
        source: ./test_dumps/mysql
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./test_dumps/data
        target: /data

  # just for testing -----
  test_postgres:
    image: postgres:latest
    container_name: test_postgres
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGPORT=5433
    volumes:
      - type: bind
        source: ./test_dumps/postgres
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./test_dumps/data
        target: /data


volumes:
  alerts-postgres-data:
  alerts-postgres-home:
  alerts-elixir-home:
